nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://ruteo.co'] # Cambia esto por tu origen permitido
            allow_headers: ['X-Custom-Auth'] # Cambia esto según tus necesidades
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600